name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prep Release
        id: prep
        run: |
          cd cli
          # Parse version
          VERSION=$(./scripts/get_version.sh)
          echo "Setting release version to $VERSION"
          echo "::set-env name=RELEASE_VERSION::$VERSION"

          # Parse changelog
          CHANGELOG=$(./scripts/parse_changelog.sh)
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"

          echo "Got changelog: $CHANGELOG"
          echo "::set-output name=changelog::$CHANGELOG"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.prep.outputs.changelog }}
          draft: false
          prerelease: false


