name: Create Release

on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Generate Changelog
      run: echo "## Changelog\n\n$(git log --pretty=format:'%h %s' -n 20)" > CHANGELOG.md
      
    - name: Add Changes in this Release
      run: echo -e "## Changes in this Release\n\n$(cat CHANGELOG.md)" > CHANGELOG.md
      
    - name: Get Pull Request Title
      id: pr_title
      run: echo "$(jq -r '.pull_request.title' ${{ toJson(github) }})"
      
    - name: Add PR Title to Changelog
      run: echo -e "$(cat CHANGELOG.md)\n${{ steps.pr_title.outputs.message }}" > CHANGELOG.md
      
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body_path: CHANGELOG.md
